apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
        - name: ai-agent
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/ai-agent:1ebec3729cd10fe1eeac6f0858fba58e2da07956
          ports:
            - containerPort: 3008
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3008"
            - name: PRODUCTS_SERVICE_URL
              value: "http://product-service:3003"
            - name: ORDERS_SERVICE_URL
              value: "http://orders:3005"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: OPENAI_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  namespace: boutique
spec:
  selector:
    app: ai-agent
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
  type: ClusterIP
